version: '3.1'

services:

  # web:
  #   environment: 
  #     DATABASE_URL: db
  #   build: .
  #   command: npm run dev
  #   ports:
  #     - "3001:8000"
  #   expose:
  #     - "3001"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "2020:8080"
    expose:
      - "2020"