version: '3.1'

services:

  web:
    environment: 
      DATABASE_URL: postgres://postgres:postgres@db:5432/CYOA
    build: .
    command: npm run dev
    ports:
      - "3001:8000"
    expose:
      - "3001"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "2020:8080"
    expose:
      - "2020"